/** Re-exports shared neutral patterns for Layer 4 classification. */
export {
  TOTAL_LABEL,
  SUBTOTAL_LABEL,
  PAYMENT_LABEL,
  DISCOUNT_LABEL,
  CHARGE_LABEL,
  VAT_LABEL,
  DATE_PATTERN,
  TIME_PATTERN,
  RECEIPT_NO_PATTERN,
  LOYALTY_LABEL,
  BARCODE_TEXT,
  SEPARATOR_TEXT,
  matchesTotal,
  matchesSubtotal,
  matchesPayment,
  matchesDiscount,
  matchesCharge,
  matchesVatLabel,
  matchesDate,
  matchesTime,
  matchesReceiptNumber,
  matchesLoyalty,
  matchesBarcode,
  matchesSeparator,
  matchesSpecialFooterLabel,
} from "../patterns/neutral";
