import {
  Baby,
  Bike,
  BookOpen,
  Building2,
  Bus,
  Car,
  Cigarette,
  Coffee,
  CreditCard,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  MoreHorizontal,
  PawPrint,
  Pill,
  PiggyBank,
  Plane,
  Plug,
  Receipt,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Stethoscope,
  Ticket,
  Train,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  utensils: UtensilsCrossed,
  cigarette: Cigarette,
  fuel: Fuel,
  shopping: ShoppingBasket,
  bag: ShoppingBag,
  coffee: Coffee,
  more: MoreHorizontal,
  heart: Heart,
  pill: Pill,
  stethoscope: Stethoscope,
  shirt: Shirt,
  home: Home,
  building: Building2,
  car: Car,
  bus: Bus,
  plane: Plane,
  train: Train,
  bike: Bike,
  receipt: Receipt,
  zap: Zap,
  water: Droplet,
  gas: Flame,
  wifi: Wifi,
  phone: Smartphone,
  card: CreditCard,
  wallet: Wallet,
  savings: PiggyBank,
  education: GraduationCap,
  book: BookOpen,
  game: Gamepad2,
  film: Film,
  ticket: Ticket,
  dumbbell: Dumbbell,
  gift: Gift,
  baby: Baby,
  pet: PawPrint,
  wrench: Wrench,
  scissors: Scissors,
  sparkles: Sparkles,
  plug: Plug,
};

export function AppIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = ICON_MAP[name] ?? MoreHorizontal;
  return <Icon className={className} />;
}
